### ISSUE TITLE
Assertive Implementers and Assertive Experts

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/wg-effectiveness#13]
>  Leads to Scope Creep / Super-Spec, Incomplete Spec, Never-Ending Discussion.

In the case of Web Payments, it's lead to the opposite (in a good way, IMO)... though I'm quite bias, because "Assertive" is my middle name :)

But seriously, we've successfully avoided scope creep, our spec specs are tiny, we've got 3 excellent specs (not "incomplete specs"), and our discussions generally last a day or two (not never-Ending discussion) because all discussions end with a pull request. 

So, I would argue that assertiveness can work, so long as it doesn't get too toxic.

**Comment by nrooney** [comment]
yeah I was trying to avoid something more obscene! I'll add "Overly" to stop people from being dissuaded into being effectively assertive!
