### ISSUE TITLE
Author Lack and Web and Mobile IG

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/wg-effectiveness#14]
> No-one from the working group is willing or qualified to write the specification. 

I think it's unfair to single out the Web and Mobile IG, because IGs are explicitly not tasked with creating specifications. 

Additionally, we pumped out pretty good documents... even if it was only 3 of us actually doing any serious work.

But the lack of author thing is on point: if a group doesn't have full time people on it, then it's unlikely to be successful or effective.

**Comment by nrooney** [comment]
True! Will remove.  Thinking about removing examples generally.

**Comment by marcoscaceres** [comment]
Yeah, maybe remove the examples... it's just going to upset groups/people who get called out.
