### ISSUE TITLE
Strong Leadership

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/wg-effectiveness#17]
Not sure I agree with this one... "Diplomatic Leadership" is probably better. For example, @ianbjacobs does an amazing job at dealing with strong personalities in the group (including me occasionally flying off the handle:)) - but he always finds a balance between views and always manages to get an outcome that everyone is can live with.

**Comment by ianbjacobs** [comment]
Thank you, @marcoscaceres.

Now back to testing!!

Ian

**Comment by nrooney** [comment]
changed
