### ISSUE TITLE
Blockers

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/wg-effectiveness#18]
In the CSI document, we should identify Blockers as a Common Cause of lack of effectiveness.

There are different kinds of blockers.  There are times when people join a WG with the objective to impede progress.  This is rare, but when it happens it is extremely disruptive.

Another kind of blocker very much wants the WG to succeed.  But only with their particular view.  They are not open to collaboration and compromise.  Finding a way to leverage their passion without disrupting the group can be very challenging for a WG.

**Comment by nrooney** [comment]
Added as "blocked"
