### ISSUE TITLE
Scope creep and continuous incubation

### ISSUE THREAD

**Issue by jeffjaffe** [w3c/wg-effectiveness#19]
In the CSI document, scope creep is (correctly) listed as a common result of ineffective groups.

In addition to being a common result - it is also a common cause.  That is, in a WG where many participants each wants to expand scope only by including their favorite feature request; that could be a cause of ineffectiveness of the group.

**Comment by jeffjaffe** [comment]
Not much has been added to this issue, so I am adding additional scoping to this issue and the beginning of how to approach the issue.  I need some discussion on the issue before I am ready for a pull request for the document.

**Additional scoping.**  This was provided by Tantek Celik at a recent AB discussion:

Here is the background.  We are evolving in practice to have incubation
before starting a WG.  It works well.  We incubate in a CG.  We then bring
it to a WG.  We are structured to have efficient WGs.

But then, once the WG is created, people have new ideas.  Whereas the ideas
that birthed the WG were well incubated; not all of the new ideas are
equally vetted.  Yet, once the WG is created, it is hard to ignore these new
ideas - even the ones that are more aspirational in nature.

**Discussion**

In order to address this issue, there requires discipline on the part of the Chair and the Working Group.  There should be a high bar to introducing new features into a spec; especially when those features have not been incubated anywhere.  

On the other hand, when there are these new features - we don't want to lose them. Even if they are not mature enough for the current specification, it is important that the ideas should not be lost.

**Proposed practice**

1. Each group should document the current features that they are working on for the specifications they are taking to Recommendation.

2. Each group should have a documented approach to dealing with incubating new features.  Some groups might specifically assign new features to be worked on in a Community Group (WASM is a recent example).  Other groups might want to incubate new features in their existing Working Group (CSS is an example).  Whatever the approach, the group should discuss and document what approach they want to use.

3. When a WG participant proposed a new feature the group should consider its disposition recognizing its incubation policy:

- If the new feature has been well incubated somewhere, it is probably a candidate to be added to what the group is currently working on.

      - Even in this case, there could be considerations why it is held off for v.next (e.g. lack of implementations, schedule delay for the document in question).

- If the new feature has not been well incubated, it should be dealt with in accordance to the group's incubation policy

     - In many cases it would be referred to a CG
     - In some cases it might be incubated within the WG - but kept apart from the REC being developed
     - In some cases, the importance of the feature might be sufficiently great that it joins the current document being developed: but this decision is made by the WG in full regard of the dangers of scope creep.

**Comment by nrooney** [comment]
Jeff - I read this again this morning and I considered two actions from this document, as just adding to the CSI document alone is probably not good enough to progress these thoughts. The proposal is:

[1] Adding a scope creep section to the "Common Symptoms" section of the document (done by adding "Overloaded Scope" - this means the term "Scope Creep" isn't confused in the doc)
[2] Starting a new doc called "Continuous Incubation", where we can properly flesh out these ideas. I took your thoughts above and created "https://github.com/w3c/wg-effectiveness/blob/master/continuous_incubation.md", where we can begin the discussion properly

**Comment by nrooney** [comment]
We can discuss in today's meeting https://github.com/w3c/wg-effectiveness/blob/master/meetings/meetings_13.md

**Comment by jeffjaffe** [comment]
@nrooney Thank you, Natasha.  Excellent.  +1.
