### ISSUE TITLE
Testing as core to spec development

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/wg-effectiveness#21]
We need to describe the central role that testing plays in the development of web standards, and particularly how WGs need to do a better job of integrating testing early into the specification development process. Specifications can't become Rec without a test suite, because the proof of interoperability is dependent on that test suite (put simply: "No tests?... no Rec!").  

The specification development process mirrors the development of open-source software in many ways. For any high-quality OSS projects, test coverage is critical for the long term health of projects, to route out bugs early, help spot security issues, prevent regressions, and to simply verify the specification. See also https://www.w3.org/TR/test-methodology/

Although testing early poses challenges to specification development, these are usually related to mismanagement of feature development, rather than to do with testing itself. For example, people wanting to see a rough shape of an API, or features, in a spec - and then fill in the gaps through incubation of those features. 

An alternative approach is to incubate features outside the spec (e.g., in a git branch and in as a github issue - which can be previewed online), which is fully tested, gets consensus, and then gets integrated into the spec proper (and possibly even implemented before actually landing in the spec!). This forces new features to be fully tested and mature before it lands into a specification. 

For what this looks like process looks like practice, see for example: https://github.com/w3c/payment-request/pull/596

## Video proposal

- [ ]  How to fix a small issue in a spec just using GitHub's Web UI. Just empowering people to fix typos is a gateway drug to:  
- [ ]  How to fix a small issue by forking, cloning, fixing, and then pushing back to GH to create the PR. 
- [ ]  How to make a PR, and how Editor's review PRs (i.e., sell the benefits of "the pull request culture" - emphasizing openness in the process, reaching consensus, and giving everyone who is invested a low friction way to participate).
- [ ]  How to use @tobie's PR Preview tool - its super easy, obviously... but people need to have that "ah ha!" moment with it, and then they can easily review and comment on specs.

We can then do a more advanced (for the groups that it applies): 

### For test contributors

- [ ]  What skills do I need? 
- [ ]  How to set up WTP locally - and serve the tests. 
- [ ]  How to convert spec text to a WP tests. 
- [ ]  How to go from a Pull Request to a WPT. 
- [ ]  How to test the IDL in a spec (what the idlHarness does and doesn't do).
- [ ]  How to write a manual test (if you really need to).  

 ### For implementers
- [ ]  Different types fo tests
- [ ]  How to set up WTP locally - and serve the tests. 
- [ ] Generating a JSON report.
- [ ] Generating a HTML report from JSON.

**Comment by astearns** [comment]
Releasing specs requires testing, but some working group participants are more interested in shipping features than working out the details in interoperability. A working group needs to have a balance of effort between shipping and testing, but keeping that balance is at the mercy of who the members send to the group. Perhaps we should take the "Working Group Attendee Roles" and split the list into "required," "nice to have," and "problematic" roles, where the tester is in the required group.

Having separate people spec and test is often quite useful. The second person interpreting spec changes in tests can help with completeness and accuracy, and point out problematic untestable assertions.

**Comment by marcoscaceres** [comment]
> some working group participants are more interested in shipping features than working out the details in interoperability. 

Isn’t that literally the absolute opposite of standardization?

**Comment by astearns** [comment]
> Isn’t that literally the absolute opposite of standardization?

I'm describing a problem working groups can face. Not everyone is fully subscribed to the W3C process and/or the desirability of test suites.

**Comment by marcoscaceres** [comment]
Right, but that’s what we are trying to fix (lack of tests is a core inefficiency - and a fundamental reason things stall). So my argument is we bake it into the process early.

**Comment by astearns** [comment]
Can you report why it hasn't worked in the cases you've seen? It went well for us in developing the CSS Shapes test suite, but I'd be interested in what failure modes could be detected and addressed.

**Comment by marcoscaceres** [comment]
> Can you report why it hasn't worked in the cases you've seen? It went well for us in developing the CSS Shapes test suite, but I'd be interested in what failure modes could be detected and addressed.

In my own case, there has been somewhat of a disconnect between the people testing and the people working on the spec (e.g., we had this problem with the orientation spec). We received no feedback to the spec from the tests, where I would have expected a flood of bugs to come in. 

Even in cases where there was a really good working relationship between non-editors providing tests (e.g., payment request), the conformance tests were found lacking ... and not thorough enough to expose interoperability problems. This meant having to almost completely rewrite the submitted tests from scratch... or even deleting some of them, because they were just wrong. 

This also lead to us writing really, um, "aggressive" crash tests (I literally managed to know out Chrome and Firefox ... pretty proud of that 🏆)... 
https://github.com/w3c/web-platform-tests/blob/master/payment-request/payment-request-constructor-crash.https.html

We also found really interesting security bugs in the spec (which we then addressed in the spec and via tests): 
https://github.com/w3c/web-platform-tests/pull/7348

Those are just some examples - and there are lots more... but since we moved from the "no tests? no merge!" model for Payment Request, we've moved much faster and greatly improved the quality and reduced the size of the spec ("if it's in the spec but not testable, DELETE IT!❤️").

**Comment by marcoscaceres** [comment]
Oh, I should also mention that we found a bunch of additional crash bugs in Chrome as part of the process, that were not caught by their own QA process. This avoided Chrome shipping buggy code, and thankfully protected users from, I think, two serious crashers (literally taking out the whole browser).

**Comment by marcoscaceres** [comment]
Fixed a few typos above... I should proof read things before hitting "comment".

**Comment by nrooney** [comment]
Ok a few things here:

* I like Alan's note about categorising Attendee Roles. I will do this now.
* Marcos, all your notes about testing make me think we need output for testing in a number of places:
  * Tests should be required in the process (this requires a process change - fun!)
  * A testing section should be built into specs, showing testing has completed (also a process change)
  * We need to detail types of tests that are required (e.g. interoperability, stress tests, security tests, etc - sad that this is evidence I know so little about tests)
  * No Tests No Merge should become a Github rule for our tools / github related outputs
  * I am also considering a team of ppl who can be approached for guidance (almost like ombudsman for testing).

Comments?

**Comment by marcoscaceres** [comment]
> Tests should be required in the process (this requires a process change - fun!)

They are already required in the process document in CR via the "[implementation experience](https://www.w3.org/2017/Process-20170301/#implementation-experience)". There is no credible way to leave CR without a test suite. 

So, we don't need to do anything 🏆 We just need to remind people that they will need a test suite to exit CR, so they might as well start it straight away. 

> A testing section should be built into specs, showing testing has completed (also a process change)

It's a tools and [work mode change](https://whatwg.org/working-mode#changes)... but no a w3c process change. 

Tool in the sense that you can use Github and the wpt infrastructure to manage this. And a work mode change in that it requires discipline: don't merge stuff into specs without tests. 
 
> We need to detail types of tests that are required (e.g. interoperability, stress tests, security tests, etc

Agree. 

>  - sad that this is evidence I know so little about tests)

For someone that claims to know so little, you got them all :)

> No Tests No Merge should become a Github rule for our tools / github related outputs

Yep. We need better tooling around this also. Improving ReSpec and BikeShed would help here too. 

> I am also considering a team of ppl who can be approached for guidance (almost like ombudsman for testing).

We have lots of great people in the community... Tobie and gsnedders, for instance (we can "@" them once we have something concrete).

**Comment by plehegar** [comment]
Note that we've improving on testing over the years and we're still working on it. To require testing would mean that we have a testing infrastructure that is suitable for everything. That will never be the case due to the nature of the territory. We can strongly encourage however. After all, I've been telling groups about the advantages of WPT over the years without requiring them and still, they're adopting it. Current strategy to get the groups to adopt a No Tests No Merge approach but that implies getting the Groups to also adopt the pull request culture as well, which is far from being the case across groups unfortunately.

Tests should be strongly encouraged. We need additional tools to keep the links between the specs and the tests (past approaches didn't succeed btw). Re details of tests, we're shooting for interop. Unfortunately, that's already a high bar so I wouldn't favor stress tests atm (it could still be a separate project). +1000 to No Tests No Merge should become a Github rule for our tools / github related outputs. See for example https://lists.w3.org/Archives/Public/public-webappsec/2017Sep/0000.html . re team of people to approach for testing: you have @sideshowbarker and @plehegar but we have the public-test-infra list as well as the #testing irc channel. We do have a testing meeting at TPAC as well as separate breakout sessions btw.

**Comment by marcoscaceres** [comment]
@plehegar, I think you've identified two great things. We know already that all, except two groups, are on github, so why don't we do some short (5 minute max) videos showing: 

 1. How to fix a small issue in a spec just using GitHub's Web UI. Just empowering people to fix typos is a gateway drug to:  
 1. How to fix a small issue by forking, cloning, fixing, and then pushing back to GH to create the PR. 
 1. How to make a PR, and how Editor's review PRs (i.e., sell the benefits of "the pull request culture" - emphasizing openness in the process, reaching consensus, and giving everyone who is invested a low friction way to participate).
 1. How to use @tobie's PR Preview tool - its super easy, obviously... but people need to have that "ah ha!" moment with it, and then they can easily review and comment on specs. 

Supplementary: 
 1. We should make all W3C repos include the json file to enable @tobie's preview tool.  

We can then do a more advanced (for the groups that it applies): 

 1. How to set up WTP locally - and serve the tests. 
 1. How to convert spec text to a WP tests. 
 1. How to go from a Pull Request to a WPT. 
 1. How to test the IDL in a spec (what the idlHarness does and doesn't do).
 1. How to write a manual test (if you really need to).  

> Unfortunately, that's already a high bar... 

You are right. This is the problem: we need to get people over that initial bar... or we need people to understand what the bar is for writing the tests (and specs!). The bar is high, and it should be: we expect surgeons to have specialized skills before they treat a person... we should expect web platform engineers to understand the platform before they add something to it (...that was a weird analogy, but you get it: the web is rocket surgery :)).

**Comment by tobie** [comment]
A video tutorial is a pretty cool idea. Might try and find the time.

**Comment by plehegar** [comment]
+1 to having tutorials. once we figured out the priorities out of the WGE TF, I'd be happy to find the resources.

**Comment by marcoscaceres** [comment]
> A video tutorial is a pretty cool idea. Might try and find the time.

I'm also happy to make some. Pretty easy to do just using QuickTime for screen recording and iMovie for titles or anything else.

**Comment by nrooney** [comment]
I can cut vids - I run Final Cut Pro for youtube vids

**Comment by marcoscaceres** [comment]
@tobie, could you check the proposed [video list](https://github.com/w3c/wg-effectiveness/issues/21#issuecomment-332409840) and let me know if you have any suggestions for additional ones (or if any should be dropped/combined, etc)?

**Comment by marcoscaceres** [comment]
BTW, I like this style of short/concise videos: https://www.youtube.com/watch?v=7Inc0G0wutk&list=PLg7s6cbtAD15G8lNyoaYDuKZSKyJrgwB-&index=2 

They are fast, punchy, and get straight to the point. No BS - you can jump in at any point to be productive. We should aim for the same.

**Comment by plehegar** [comment]
So, https://w3c.github.io/workflow.html is now live. Biggest is that it's using the CLI, rather than a GUI. Looking to see to add GUI documentation as well but question is which GUI to recommend. @iherman uses SourceTree which seems a good candidate.

**Comment by nrooney** [comment]
@tobie when you have a sec will you check the video list @marcoscaceres added above, then he'll get started making them and we can look forward to his dulcet tones teaching us the magic of testing for the web!

**Comment by tobie** [comment]
Sorry, I somehow missed https://github.com/w3c/wg-effectiveness/issues/21#issuecomment-336346820.

To answer your questions, I don't feel like I have a good enough idea of the bottlenecks felt by folks new to standardization and/or modern distributed versioning tools. So before establishing a list and doing videos, I'd go talk to them, compile a resource center with existing resources that would help them out, and then eventually fill the gaps (or the key issues, or both) with videos. That said you probably have a clearer picture of where they're at than I do.

**Comment by marcoscaceres** [comment]
> To answer your questions, I don't feel like I have a good enough idea of the bottlenecks felt by folks new to standardization and/or modern distributed versioning tools. 

Understood. I'm going from my own experience, and from trying to teach others, over the last year.  

> So before establishing a list and doing videos, I'd go talk to them, compile a resource center with existing resources that would help them out, and then eventually fill the gaps (or the key issues, or both) with videos. 

The problem is that "them" don't exist (or if they do, they've figured it out already) - we are trying to create "them" :) That is, there are people who are curious about testing, heard it's a good thing, but know/sense that the process is going to be challenging. 

The videos should get someone up and running - and allow them to evaluate if they can actually make meaningful contributions. In the majority of cases (I would say 95%), most people will run for the hills: if you are not on Unix/OSX, and don't know JS/HTML pretty well, one is fairly screwed. 

That's ok, tho. Those that we don't lose in the first few minutes could really help. 

I'm also realizing that there are actually two audiences here:

 * test contributors. 
 * implementers - seeking to check if they conform.

**Comment by tobie** [comment]
Ok, it wasn't clear (to me) that your audience for your list was future testers. 

The concern I have is whether anything is stable enough at this point that your video won't be outdated too quickly.

**Comment by marcoscaceres** [comment]
> The concern I have is whether anything is stable enough at this point that your video won't be outdated too quickly.

Understood. It's why I'd like to keep everything super-low budget and no more than 5mins. 

However, if there are things we know are about to change - then we can definitely put those things off.

**Comment by nrooney** [comment]
If @tobie is cool with the super-low-budget vids then we can get making! @marcoscaceres were you going to do these yourself or do you want help? I can help with editing!

**Comment by nrooney** [comment]
Pushing conversation to Process repo: https://github.com/w3c/w3process/issues/157
