### ISSUE TITLE
Supergroups vs smaller time limited groups

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#23]
A few people have commented that smaller time limited groups are more effective than supergroups (although they do also understand why some supergroups exist). Should we give some direction in how to create working groups to be small and time limited?

**Comment by astearns** [comment]
At the very least, smaller well-scoped groups should be the norm. The consortium should try to redirect any aspirations to create/become new supergroups.

**Comment by marcoscaceres** [comment]
I don't know... tbh... I think you can have super groups, but then have small, well-managed, projects for each spec. In some ways, WebApps works well that way... in that if a project is well staffed with skilled people, then stuff gets done effectively.

**Comment by jeffjaffe** [comment]
There are many reasons for supergroups.  CSS is one cohesive community with a long running mission.  I think some members like the Web Platform Supergroup for IPR coverage. Not clear that one size fits all.

**Comment by nrooney** [comment]
Thanks for the comments all. Will close and note the valuable discussion
