### ISSUE TITLE
TO ALL: Happy with the suggested Output?

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#24]
The group's suggested output has been added to the README.md file:
[](https://github.com/w3c/wg-effectiveness)

Do you think everything has been covered? Is there something else the group should be doing? Please also take a look at the [questions](https://github.com/w3c/wg-effectiveness/blob/master/meetings_3.md) we have been answering on the calls. Do you think the output answers all the concerns identified by discussing the questions?

**Comment by dontcallmedom** [comment]
My feedback on the proposed outcomes, which I understand to be:
* Process
* CSI
* Ombudsman
* Guide & github
* Testing
* Chair training

First feedback - this is a long list, so we should at least prioritize it or we're unlikely to achieve anything. I suggest trimming it below.

On individual items:
* Process: I would not make this a focused outcome; if we stumble on things that block us in the process, we should file issues with the Process CG; and I would stay clear from trying to push new requirements unless we have very strong reasons to believe the process is the right way to push/enforce changes 
* CSI development sounds good, although I would focus on practical remedies at this stage more than the analysis framework; I'm not sure I understand what the Triage Process would be
* Ombudsman - I think an Ombudsman is needed when there is a specific need for a neutral arbiter, independent of the normal course of actions. It's not obvious that it is needed here; if there was, I don't think plh would not qualify as neutral given he's supposed to oversee the normal course of actions
* +1 on a drive to update the guidebook; I think a key part is also designing workflows to not make this a one-off, but something that would more naturally occur on a regular basis
* Testing: +1 on documenting testing best practices, nudging (but probably not Process-requiring) groups to apply them
* Chair training: +1 on strengthening the program by working with chairs on whether and how they would like to get trained / exchange with their peers

**Comment by marcoscaceres** [comment]
I also agree with @dontcallmedom about reducing the scope, and also would like us to focus on only 3 things (guidebook, testing, and chair training). 

If we can achieve something with just those three, that's already a pretty big win.

**Comment by nrooney** [comment]
Yeah seems sensible. Maybe we can divide these into "now" and "possibly later" (with better terms) to make sure our scope is strict but we're not outrightly dismissing any good ideas.

**Comment by nrooney** [comment]
Output seems to be agreed, no one else has commented so closing issue.
