### ISSUE TITLE
Github by default?

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#25]
Should working groups use github by default? It seems through some conversations I've had in various groups people generally agree that groups should be using github for specs. Let me know your thoughts!

**Comment by marcoscaceres** [comment]
It's really about using a space that facilitates collaboration, provides issues tracking, and where the community is. Today, that's github. I don't think it should be a hard requirement tho. It's just the logical choice (today)... same with using git... but tomorrow, who knows.

**Comment by plehegar** [comment]
I agree. The thing, we're building a lot of tools on top of the GitHub API nowadays so switching will be difficult but not impossible. Nowadays, a WG would need to present a strong case for not using GitHub given our tooling base.

**Comment by plehegar** [comment]
btw, note that the publication requirements now indicates that every newly published W3C Rec must have a link to a GitHub issues list. This is intended to facilitate the maintenance tracking:
 https://www.w3.org/pubrules/doc/rules/?profile=REC#mailingListName

**Comment by nrooney** [comment]
Ok cool. We can write guidelines and tips for using gh then without hard requiring it. I should check this with @LJWatson as to whether this lines up with the AB tools plans.

**Comment by plehegar** [comment]
I'm proposing to add more to our GitHub documentation to recommend the pull-request-and-test workflow.

**Comment by nrooney** [comment]
Seems we're agreed that github should be very strongly recommended, but not necessarily enforced. Using github will therefore be strongly recommended in the new w3c.github.io
