### ISSUE TITLE
Qualifying some of the required working group role list

### ISSUE THREAD

**Issue by astearns** [w3c/wg-effectiveness#28]
@nrooney you noted that the number of required roles in the list is fairly long. Perhaps we could take the various expert roles and put them in a Required/Outsourced section (probably with a better name). These roles are where it's necessary to have someone with that expertise involved in the group. If you don't have someone with that expertise in the group proper, then you need to make extra sure your wide review includes people with that expertise.

**Comment by nrooney** [comment]
Ah great idea! I'll make the change

**Comment by nrooney** [comment]
Added - not sure on language still
