### ISSUE TITLE
Questions for Chairs at TPAC and on Questionnaire

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#29]
At chair's breakfast. Make a set of questions to get answers.

**Comment by nrooney** [comment]
Leonie mentioned we open a survey "name three things that you wish you'd have known at the beginning of being a chair"

**Comment by plehegar** [comment]
1. Name three things that you wish you'd have known at the beginning of being a chair
2. Which W3C Process step(s) would you like to see simplify or removed?
3. Which tool would you like to have or get improvements on?

**Comment by astearns** [comment]
What is the one thing currently hindering your working group's effectiveness you'd like help with?

**Comment by nrooney** [comment]
From #30 : "name three things that you wish you'd have known at the beginning of being a chair"

(this was a question we wanted to get asked as a questionnaire

**Comment by nrooney** [comment]
Ask questions about using github, and thoughts on moving to a pull request mechanism (also helps promote the pull request method)

**Comment by nrooney** [comment]
We use https://www.w3.org/2002/09/wbs/showwb for making surveys and questionnaires

**Comment by nrooney** [comment]
Existing training done here: https://www.w3.org/wiki/AB#W3C_Chairs_Training
