### ISSUE TITLE
Chair Onboarding Process

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#35]
As discussed in the Chairs Breakfast. Please drop any tips or recommendations here for what should be in the chairs onboarding process.

**Comment by nrooney** [comment]
From @nigelmegitt 

--
Just to note that an onboarding process for members was also discussed, and there may be overlap, for example anything that covers culture, organisational norms etc. Or alternatively perhaps the Chair onboarding is dependent on Member onboarding having been completed.
--

**Comment by tantek** [comment]
IMO since w3t chooses chairs, w3t should also own (be responsible for) chair on boarding. I believe @michaelchampion may have said something like this informally at the chairs breakfast though I don't remember if it was out loud or an aside.

**Comment by nrooney** [comment]
We're working on some mails to send to chairs, as well as getting /guide sorted. Hopefully the onboarding process can be detailed in /guide and mails can help point them in the right place for info.

**Comment by nigelmegitt** [comment]
I'm not sure about the resourcing commitments but having a human check in with the new Chair a couple of times after beginning work, at set intervals, e.g. 1 week, 1 month, 3 months, 6 months, to review performance, provide Chair mentoring etc might not be a bad idea. Someone to say "pattern X is happening here, I've seen that before, it's `[causing you a problem|showing the group is working effectively]`, so `[intervene|continue as is]`." in a direct and honest manner in private, would be more useful than any amount of documentation that busy Chairs might not have time to read.

**Comment by nrooney** [comment]
Leaving this to the team seems sensible. We've written some emails to help with welcoming chairs in this repo; aside from this team contacts should check in with chairs as suggested by @nigelmegitt above.
