### ISSUE TITLE
Review Process Document for Busy People

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#42]
cut down content, rearrange items, Current layout is:

* The process document
    * Updating the Process Document
* Setting Up Interest and Working Groups
    * Charters
    * Group Extensions
* W3C Recommendations 
    * Requirements for W3C Recommenations (Technical Reports)
    * Editors
    * Language
    * W3C Recommenation (Technical Report) Flow: The "Recommendation Track” 
        * Editors Drafts
        * Working draft
        * CR
            * Revised CR
        * PR
        * W3C Rec
    * Tranition Requests and Moving Between Track Stages  
    * Ending a Document
    * Reviewing Documents
    * Implementation Experience
    * Document Changes <xxxxx>
    * Modifying a W3C Recommendation
        * Revised Recommendation (Edited and Amended Recommendations)
        * Rescinded, Obsolete or Superseded Recommendations
* Member Submissions
* Understanding W3C Members
    * members
    * Membership Consortia
* Leadership and Leadership Groups
    * Director
    * AC
        * AC reviews
        * AC appeals
    * AB
    * TAG
    * Team 
* W3C Interest and Working Groups
    * Groups 
    * Particpants
        * Participation by Proxy
    * Group size
    * Charter and Call for Participation
        * Charter contents
        * Charter extensions
    * Closing a group
    * meetings
    * Consensus and formal objections
        * Group Decision Appeals and Formal Objections
    * Votes
* Communication
    * Confidentiality Levels
* Workshops and Symposia
* Liaisons
* Terms

**Comment by wseltzer** [comment]
@nrooney, You've done an admirable job shortening the document, but it remains a long pProcess.

I wonder what particular busy people you have in mind, and whether some of them would find it more helpful to have chunks of workflow than the entire process summarized. For example, "Process bits relevant to AC reps" differs from "Process bits relevant to chairs" and "Process relevant to WG participants."

**Comment by nrooney** [comment]
Closing. Shortening the doc is given in #53
