### ISSUE TITLE
Buddy System - how should it work?

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#43]
How should the buddy system work? Shall we canvas the chairs for buddies and people who want buddies and then start pairing up?

**Comment by RachelComerford** [comment]
Is the buddy system like what we experienced at TPAC where a more experienced member helped a less experienced member?  Would it be helpful if we constructed a list of expectations/requirements for the more experienced buddy, and some sort of feedback loop (especially at the introduction of the system) so we can ensure that the benefits are consistent?

**Comment by nrooney** [comment]
Closing this as managing as part of #63
