### ISSUE TITLE
meta: how does one join the TF? who can/should join?

### ISSUE THREAD

**Issue by tantek** [w3c/wg-effectiveness#46]
In writing up https://www.w3.org/wiki/AB#Working_Group_Effectiveness_Task_Force I realized there was no obvious way to join the TF, nor clarity on who can/should join?

The README should be updated to clarify:
* How to join the TF (who to contact)
* Who should (can) join

**Comment by nrooney** [comment]
Should be solved by last pull request, if not, please reopen!
