### ISSUE TITLE
Opening/resolving issues effectively

### ISSUE THREAD

**Issue by RachelComerford** [w3c/wg-effectiveness#50]
One the major struggles that we face in the groups I participate in is in getting productive responses to issues. Too often I see thinly disguised sarcasm, personal complaints that are unrelated to finding a solution, or a long list of reasons why something won't work without any proposed solutions. In problem solving, I try to ask participants to answer the following questions:

1. What problem are you trying to solve?
2. What solution are you proposing?
3. Why do you believe this is the ideal solution?
4. What alternatives did you consider
5. What is your back up plan?

Consistency in enforcing these structured responses is difficult (and I admit to struggling with it) but without this, I see newer members to groups and in particular newer members to the W3C/W3C processes alienated by lack of explanation of methods, uninterpretable proposals, and (in my opinion the worst offense) the attitude that can sometimes accompany experience.

While it will be difficult to convince some member to abide by guidelines like this, I think it would be a beneficial structure (or something like it would be) to recommend in order to help keep github conversations civil and effective.

**Comment by nrooney** [comment]
Re-reading this now and am attempting to work out the best place to publicise it so chairs can find this suggestion and encourage their participants to start responding in this way. This may also help with #68

**Comment by nrooney** [comment]
Continues on https://github.com/w3c/Guide/issues/27
