### ISSUE TITLE
Uncap "Leadership and Leadership Groups "

### ISSUE THREAD

**Issue by wseltzer** [w3c/wg-effectiveness#57]
Since "Leadership and Leadership Groups" is not a defined term, drop the caps.

**Comment by nrooney** [comment]
Titles in written english have words in caps except for connecting words like as, in, of, and etc.

**Comment by astearns** [comment]
Right, but the instance in the paragraph under the title shouldn't be capitalized.

**Comment by nrooney** [comment]
Goos point! Changed!
