### ISSUE TITLE
buddy system next steps

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#63]
page, email, then push at tpac

**Comment by nrooney** [comment]
Add tips for team members: preference to assign buddies who you do not know

**Comment by nrooney** [comment]
make sure not enforcing times of when to speak - allow buddies to be flexible and make their own schedule

**Comment by plehegar** [comment]
per Aug 8, I'm going to push for this.

**Comment by nrooney** [comment]
plh can report on the calls for this - open issue not needed.
