### ISSUE TITLE
Explainers - need to write for /guide

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#66]
helpful for business requirements.

**Comment by nigelmegitt** [comment]
Quick attempt at fleshing this out:

It's possible to get a spec to Rec without ever defining what job it is trying to do. You just need to write the spec and tests for implementation, and show that two implementations pass the tests that do what the spec says.

**But**, that doesn't tell you that the spec does something useful in the first place. That should come from testable business requirements, which could be expressed as "behaviour driven development" tests, i.e. "Given x, when y happens then z should be the result". Then you can write the spec against those, test implementations against spec, and close the loop by verifying that those implementations also meet the original business requirements.

At the moment our only criterion for advancing to Rec is that enough people are willing to implement, which is a mid-level proxy for "we think it is actually useful".

**Comment by nrooney** [comment]
So could a suggestion be that an "Explainer" doc (that some specs create on their github repo) is enough? Or is there a case to add a section to the actual spec itself?

I've always liked the explainer doc idea - maybe we could either encourage chairs to create such a thing or make a template to help them get started?

**Comment by RachelComerford** [comment]
+1 for a template... if we can standardize the questions being answered in the explainer it will make it easier for new users to acclimate.

**Comment by nrooney** [comment]
Rachel's questions would be good to add to this template

**Comment by nrooney** [comment]
Is adding items to /guide enough here?
