### ISSUE TITLE
how to handle a bully

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/wg-effectiveness#68]
I have been hearing about bullies in WGs. I have had to deal with one myself. It is nice to talk about WG Effectiveness, but one bully derails everything. What concrete actions should a chair/Team take when there is a bully? At what point does a bully's behaviour outweigh his or her contributions? This might overlap with [PWETF](https://www.w3.org/Consortium/pwe/).

**Comment by nrooney** [comment]
We have "Overly Assertive" people issues detailed in the CSI doc; but I can see this problem would need more than this.

I like the idea of an ombudsman to help with this - for chairs and people unfortunately being bullied.

https://github.com/w3c/wg-effectiveness/blob/master/CSI.md

**Comment by nigelmegitt** [comment]
Sometimes it is not clear if a behaviour is merely assertive or overly assertive but should rightly be called out as bullying. It'd be good if such an ombudsman could be called on to provide guidance.

**Comment by kcoyle** [comment]
The problem is defined there, but we do need a way to resolve this. Folks who are pushing hard for their solution can try to shut down all other possible solutions. Some do it gently, but some are less so, and people stop discussing when every idea is shot down. In meetings I've found that I can often just call on someone else to move the discussion on, but on email and github that doesn't work because: asynchronous. (Interestingly, in my experience the harsh behavior happens more online than in meetings.)

**Comment by kcoyle** [comment]
Here's a definition of bullying:

"Bullying is conduct that cannot be objectively justified by a reasonable code of conduct, and whose likely or actual cumulative effect is to threaten, undermine, constrain, humiliate or harm another person or their property, reputation, self-esteem, self-confidence or ability to perform."

http://bullyonline.org/index.php/what-is-workplace-bullying

Here's some of the behavior that I'm seeing, and its effect:

"You're wrong." Shuts down the conversation or turns it antagonistic. Definitely derails brainstorming. Scares away shyer folks.

"You're ALL wrong." Does not accept group's consensus. 

"You're saying it wrong." Correcting people's terminology during informal discussion, almost always as part of not listening to what they are saying but only how they are saying it. Interrupts the flow of discussion (which may be the goal).

"Mine is better." Refusal to accept ideas offered by others but constant push for something others aren't interested in. 

I'm sure others can add to this ;-)

**Comment by torgo** [comment]
Hi - I would add the "I alone am the spokesperson of the developer community" syndrome. I've seen this in many contexts - and it's definitely a form of bullying. Also, responding to a detailed and thoughtful post or question with a curt "you didn't understand me" or "you obviously don't understand / didn't read xxx" or "what part of xx didn't you understand" is a form of bullying. Both of these are (in my view) examples of responses to a question or comment that are not intended for the actual recipient...

**Comment by nrooney** [comment]
Tink mentioned we could help chairs in understanding when this may be happening, /guide is a good place.

Alan said it would be good to include in /guide what remedies could be. Ban from irc, ban from github issues

Code of conduct implementation document may be the best place for this.

**Comment by nigelmegitt** [comment]
> Ban from irc, ban from github issues

How can this practically be achieved?

**Comment by astearns** [comment]
The one instance I had to make an actual ban was to a mailing list, and sysreq helped me with that (after making a strong case that we were only getting abuse from this person and not also anything useful)

For GitHub we have only cautioned people and deleted abusive comments, which has been enough push-back to stop things so far. Staff with access to the org settings would be able to block people from all of our repos (I assume you'd have to make a strong case for this)

https://help.github.com/articles/blocking-a-user-from-your-organization/

And we've had people kicked and banned from IRC with ops powers - I recall looking up the commands and flailing about with them once, but I don't remember the details. That's pretty easy to circumvent, but the cooldown period you get with a kick is usually enough for people actually engaged (as opposed to spammers)

**Comment by nigelmegitt** [comment]
Thanks @astearns that's pretty much what I expected.

**Comment by jeffjaffe** [comment]
I would like to see some discussion about how to coach bullies.  While there may be some bullies who are just bullies; I believe that others may be passionate advocates of some position that do not realize how their passion is viewed and interpreted by others.
