### ISSUE TITLE
Ombudsperson

### ISSUE THREAD

**Issue by nrooney** [w3c/wg-effectiveness#76]
Start fleshing out the idea for an Ombudsperson, there should be around 3 people and they should be ombudsperson for PWE, WGE and code of conduct.

**Comment by nrooney** [comment]
Started https://github.com/w3c/wg-effectiveness/blob/master/ombudsperson.md

**Comment by nigelmegitt** [comment]
The draft currently says

> Ombudspeople MUST respect that conversations they have as an Ombudsperson MUST remain anonymous

I think there should be an option for confidentiality as an alternative to anonymity.

**Comment by nrooney** [comment]
Sent to PWE
