### ISSUE TITLE
Process for Busy People needs Director-free update

### ISSUE THREAD

**Issue by svgeesus** [w3c/wg-effectiveness#97]
The [Process for Busy People](https://github.com/w3c/wg-effectiveness/blob/main/process.md#the-director) has 37 mentions of the Director, and in the light of the [changes in Process 2023](https://www.w3.org/2023/Process-20230612/#changes-2021) should be updated to use [W3C Decision](https://www.w3.org/2023/Process-20230612/#decision-types), [W3C Council](https://www.w3.org/2023/Process-20230612/#council), Team and so on as appropriate.

**Comment by AramZS** [comment]
Was just reviewing this and noticed the same issue.

**Comment by svgeesus** [comment]
PR here https://github.com/w3c/wg-effectiveness/pull/98
